dataset:
  train:
    _base_: cfgs/dataset/TreeDatasetHELIALS.yaml
    others:
      K_FOLDS: 1
      bs: 16
      subset: train
  val:
    _base_: cfgs/dataset/TreeDatasetHELIALS.yaml
    others:
      K_FOLDS: 1
      bs: 16
      subset: val
  test:
    _base_: cfgs/dataset/TreeDatasetHELIALS.yaml
    others:
      K_FOLDS: 1
      bs: 16
      subset: test
grad_norm_clip: 10
max_epoch: 250
model:
  NAME: PointNet2_MSG
  channels: 3
  dropout: 0.5
  label_smoothing: 0.0
  mlp3:
  - 640
  - 256
  - 512
  - 1024
  mlps1:
  - - 0
    - 32
    - 32
    - 64
  - - 0
    - 64
    - 64
    - 128
  - - 0
    - 64
    - 96
    - 128
  mlps2:
  - - 320
    - 64
    - 64
    - 128
  - - 320
    - 128
    - 128
    - 256
  - - 320
    - 128
    - 128
    - 256
  npoint1: 512
  npoint2: 128
  nsamples1:
  - 16
  - 32
  - 128
  nsamples2:
  - 32
  - 64
  - 128
  num_classes: 9
  radii1:
  - 0.1
  - 0.2
  - 0.4
  radii2:
  - 0.2
  - 0.4
  - 0.8
npoints: 2048
optimizer:
  kwargs:
    lr: 0.0005
    weight_decay: 0.0001
  type: AdamW
scheduler:
  kwargs:
    initial_epochs: 10
  type: CosLR
step_per_update: 1
