dataset:
  train:
    _base_: cfgs/dataset/TreeDatasetHELIALS.yaml
    others:
      K_FOLDS: 1
      bs: 16
      subset: train
  val:
    _base_: cfgs/dataset/TreeDatasetHELIALS.yaml
    others:
      K_FOLDS: 1
      bs: 16
      subset: val
  test:
    _base_: cfgs/dataset/TreeDatasetHELIALS.yaml
    others:
      K_FOLDS: 1
      bs: 16
      subset: test
grad_norm_clip: 10
max_epoch: 250
model:
  NAME: DeepGCN
  act: relu
  bias: true
  block_type: res
  c_growth: 64
  channels: 64
  conv: edge
  dropout: 0.5
  emb_dims: 1024
  epsilon: 0.2
  k: 20
  knn: matrix
  label_smoothing: 0.0
  n_blocks: 14
  norm: batch
  num_classes: 9
  stochastic: true
  use_dilation: true
npoints: 2048
optimizer:
  kwargs:
    lr: 0.0005
    weight_decay: 0.0001
  type: AdamW
scheduler:
  kwargs:
    initial_epochs: 10
  type: CosLR
step_per_update: 1
