dataset:
  train:
    _base_: cfgs/dataset/TreeDatasetHELIALS.yaml
    others:
      K_FOLDS: 1
      bs: 16
      subset: train
  val:
    _base_: cfgs/dataset/TreeDatasetHELIALS.yaml
    others:
      K_FOLDS: 1
      bs: 16
      subset: val
  test:
    _base_: cfgs/dataset/TreeDatasetHELIALS.yaml
    others:
      K_FOLDS: 1
      bs: 16
      subset: test
grad_norm_clip: 10
max_epoch: 250
model:
  NAME: PointTransformer
  channels_input: 3
  label_smoothing: 0.0
  num_classes: 9
npoints: 2048
optimizer:
  kwargs:
    lr: 0.0005
    weight_decay: 0.0001
  type: AdamW
scheduler:
  kwargs:
    initial_epochs: 10
  type: CosLR
step_per_update: 1
